name: build
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build binary to make sure it works
        run: go build -mod vendor
      - name: Test
        run: go test -mod vendor ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.txt
      - name: Get image repository
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          pull: true
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}
